### ISSUE TITLE
Release and CI - avoid automatic releasing / publishing of new image if there aren't any changes in the image

### ISSUE THREAD

**Issue by kabirbaidhya** [laudio/pyodbc#14]
**Current Behavior**
For any commit pushed into the `master` branch, CI will automatically release a new tag and publish a new docker image for `laudio/pyodbc` to docker hub. 

If there has been really a change in the actual docker image or the contents of the image eg: Dockerfile, requirements.txt etc it makes sense to release a new image. But several times there have been changes pushed including only the documentation update, tests, example code, etc which doesn't bring any change in the actual image - in these cases releasing a new tag and the image doesn't make sense.

**Expected Behavior**
Update CI / release script to not release a new image if the actual docker image hasn't changed or any of the underlying dependencies of the image hasn't changed. For example for the changes like doc updates, examples, addition of new tests etc which shouldn't get a new version bump.

**Comment by enflo** [comment]
I have created a pullrequest with a possible solution, I hope it is to your liking. Any doubt I am at your disposal to solve it  #15
