### ISSUE TITLE
Example improvements - Print the number of rows transferred

### ISSUE THREAD

**Issue by kabirbaidhya** [laudio/pyodbc#20]
Need to print an INFO message here on how many rows were transferred.
 
For example: 
```
Transferred 3 rows of fruits data from source {database} to destination {database}.
```

_Originally posted by @kabirbaidhya in https://github.com/laudio/pyodbc/pull/19_

**Comment by shradayshakya** [comment]
[Here is my PR](https://github.com/laudio/pyodbc/pull/21/files)
