### ISSUE TITLE
Add static typing for all the python code base

### ISSUE THREAD

**Issue by kabirbaidhya** [laudio/pyodbc#22]
Enable static typing for all the python codebase (tests, examples). The base image already uses python >= 3.6 which supports static typing - we should make good use of it. 

Reference: https://docs.python.org/3/library/typing.html#module-typing.

**Note:** some part of the existing code already has types - eg: [here](https://github.com/laudio/pyodbc/blob/master/examples/data-transfer-pg/main.py#L38-L72) - this has to be done consistently where ever possible.

**Comment by yankeexe** [comment]
I will be taking this issue.
