### ISSUE TITLE
Configure and Integrate microsoft/pyright in the CI to enforce static typing

### ISSUE THREAD

**Issue by kabirbaidhya** [laudio/pyodbc#23]
**Requirements:**
 - Configure & Integrate this - https://github.com/microsoft/pyright
 - Add guidelines in the README to run it on the local. 
 - Travis Integration to validate code changes in the pull requests.

**Comment by mesaugat** [comment]
Let's wait for a bit. If someone doesn't show up, I can do it.

**Comment by yankeexe** [comment]
@mesaugat @kabirbaidhya I have created a new PR for this issue, please review it.
