### ISSUE TITLE
Add examples for usage with MySQL

### ISSUE THREAD

**Issue by kabirbaidhya** [laudio/pyodbc#32]
Add examples for usage with MySQL. 

Need two examples:

- [x] Basic Example (under `examples/app-mysql`) (#41)
- [x] Data Transfer Example (under `examples/data-transfer-mysql`) (#43)
 
Check the existing [examples ](https://github.com/laudio/pyodbc/tree/master/examples) for mssql and pg first before starting as the everything needs to follow the same convention and structure with mysql.

**Comment by parwatcodes** [comment]
I'll be working in it.

**Comment by yankeexe** [comment]
I will be doing this.
