### ISSUE TITLE
Support MySQL and add tests to verify database connection works

### ISSUE THREAD

**Issue by kabirbaidhya** [laudio/pyodbc#33]
Test to ensure MySQL connection works.

**Requirements**
- Add MySQL ODBC driver
- Add test for MySQL connection
- Integrate it in Travis

Take reference from PR https://github.com/laudio/pyodbc/pull/1 on how it's done for Postgres and MSSQL; need to add MySQL in that.

Review existing tests here https://github.com/laudio/pyodbc/tree/master/test

**Comment by parwatcodes** [comment]
I'll be working in it

**Comment by SafalPandey** [comment]
@p0k8h We need to install ODBC drivers for mysql in the pyodbc image (`base` stage) before adding tests for mysql.

cc: @kabirbaidhya

**Comment by kabirbaidhya** [comment]
Yes. Thanks for pointing out before the test could catch this even. :smile:
