### ISSUE TITLE
Image support for ARM64 arch

### ISSUE THREAD

**Issue by wdoogz** [laudio/pyodbc#63]
Hello, I am currently a developer who uses the laudio/pyodbc container image.
I was wondering if there would be a way to get support for Apple Silicone products with M1/M2 chips.

This should help anyone running on an arm64 raspberry pi as well.
Currently there is only support for X86_64.

If you do not have access to test on a Mac or other arm64 box please let me know I am more than happy to help test :)
Example of issue
```
docker pull laudio/pyodbc
Using default tag: latest
latest: Pulling from laudio/pyodbc
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by wdoogz** [comment]
Tagging @mesaugat for your visability 😃

**Comment by mesaugat** [comment]
@wdoogz I can take a look when I find the time. I can build arm64 images on my machine.

**Comment by mesaugat** [comment]
The new pyodbc release seems to have better support for Mac ARM processors. https://github.com/mkleehammer/pyodbc/releases/tag/5.1.0

This means it should be easier to add support for arm64.

**Comment by mesaugat** [comment]
@wdoogz New version `laudio/pyodbc:3.0.0` has been released. Please try it out and report bugs if any.

https://github.com/laudio/pyodbc/releases/tag/3.0.0
