### ISSUE TITLE
Setup an example project using mssql

### ISSUE THREAD

**Issue by kabirbaidhya** [laudio/pyodbc#7]
Add an example project using mssql database connection.

**Requirements:**
 - Create a project `examples/app-mssql`. 
 - Should have dockerfile make use of laudio/pyodbc as a base image. 
 - App should make mssql connection and demonstrate running few queries on it
 - Should have `docker-compose.yml` with two services - mssql and app; so running `docker-compose up` should run the app.

**Comment by v1shwa** [comment]
Hey @kabirbaidhya I can work on this, can you assign this to me.
