### ISSUE TITLE
Setup an example project using postgres

### ISSUE THREAD

**Issue by kabirbaidhya** [laudio/pyodbc#8]
Add an example project using postgres database connection.

**Requirements:**
 - Create a project `examples/app-pg`. 
 - Should have dockerfile; make use of laudio/pyodbc as a base image. 
 - App should make postgres db connection and demonstrate running few queries on it
 - Should have `docker-compose.yml` with two services - pg and app; so running `docker-compose up` should run the app.

**Comment by sravyasri** [comment]
Can I pick it up? #hacktober

**Comment by kabirbaidhya** [comment]
@sravyasri Sure you can.

**Comment by kabirbaidhya** [comment]
This has been done in https://github.com/laudio/pyodbc/pull/17 by @shradayshakya.

cc @sravyasri
